database_name: 
knowledge_base_description: financial advisor
knowledge_base_id: 
knowledge_base_name: 
project_name: financial-advisor
project_short_name: fa
region_name: us-west-2
s3_bucket_name_for_athena: 
s3_bucket_name_for_kb: 
